spring:
  datasource:
    url: jdbc:mysql://localhost:3306/redis?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
  main:
    allow-bean-definition-overriding: true

  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
